spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://${DB_URL:localhost}:3306/${DB_NAME:jwt-test}?useSSL=false&characterEncoding=UTF-8&serverTimezone=Asia/Seoul&allowPublicKeyRetrieval=true&tinyInt1isBit=false&rewriteBatchedStatements=true
    username: ${DB_USERNAME:root}
    password: ${DB_PASSWORD:1234}

  jpa:
    hibernate:
      ddl-auto: create
    properties.hibernate:
      format_sql: true
      show_sql: ${SHOW_SQL:false}
      jdbc:
        batch_size: 200
    open-in-view: false

  jackson:
    property-naming-strategy: SNAKE_CASE

easy-jwt:
  access-exp: 3600
  refresh-exp: 36000
  secret: dsjadkujaiodsuoajdoisajdiosajdiosa